### ISSUE TITLE
toxicity not working

### ISSUE THREAD

**Issue by songproducer** [uber-research/PPLM#12]
>python3 run_pplm.py -D toxicity --class_label 3 --cond_text "The food is aweful" --length 50 --gamma 1.0 --num_iterations 10 --num_samples 3 --stepsize 0.04 --kl_scale 0.04 --gm_scale 0.95 --sample

```
Traceback (most recent call last):
  File "run_pplm.py", line 794, in <module>
    run_pplm_example(**vars(args))
  File "run_pplm.py", line 621, in run_pplm_example
    pretrained_model = DISCRIMINATOR_MODELS_PARAMS[discrim]["pretrained_model"]
KeyError: 'toxicity'
```

**Comment by dathath** [comment]
We only made the pre-trained clickbait and sentiment discriminator models publicly available. If you're interested in the toxicity model, we can share privately. Alternative, the training script in the repository can be used to train one yourself in a few minutes.

**Comment by songproducer** [comment]
I don't have a nvidia card - I have a 2017 imac pro. Is it feasible to train on this?

If so, how can I run the training script? I noticed in the script it makes a reference to datasets/toxic/toxic_train.txt but I don't have this folder setup or file

**Comment by dathath** [comment]
I think you might need a GPU to train, but should take less than 10-15 minutes. So, if you can use a cloud GPU instance or something for half an hour, that could work. If you cannot, let us know.. we will see if we can train/share a pre-trained discriminator.

You can get the dataset from https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge. You will need to wrangle to the dataset to the relevant format and also turn it into into a binary classification problem (all types of "toxic" as one class, and normal text as the other). 

The original code for the paper comes with a pre-trained [classifier.](https://github.com/uber-research/PPLM/blob/master/paper_code/discrim_models/toxicity_classifierhead.pt) However, the original code is not cleaned up --  if you can figure out how to run the original code for the paper, you can try using the discriminator there. Due to some minor changes in the hugging-face repo (the paper uses an older GPT-2 implementation), the discriminator from the old code (linked above) won't work well with the newer code (the one you are working with right now).

**Comment by songproducer** [comment]
I appreciate your help and direction but I'm just beginning to learn about machine learning and haven't worked out how to train anything yet so unsure how to proceed with changing the format into a binary classification problem.

I downloaded the jigsaw-toxic-comment-classification-challenge data and have these files:
sample_submission.csv, test_labels.csv, test.csv, train.csv
but I'm flying in the dark so don't know how to use these files.

I am keen to try some other discriminators other than clickbait and sentiment. If I use:
 --discrim_weights toxicity_classifierhead.pt
what file do I need to use for:
--discrim_meta
?
