### ISSUE TITLE
Time to train an attribute model

### ISSUE THREAD

**Issue by bilal2vec** [uber-research/PPLM#6]
Hi

I'm training my own attribute model with 

```python
python run_pplm_discrim_train.py --dataset SST --pretrained_model distilgpt2 --epochs 1 --log_interval 100
```

in colab with the gpu and it's taking about 3s/batch. Is this normal?

Thanks

**Comment by dathath** [comment]
I think it's because the inputs to the attribute model aren't cached. Note that the forward passes through the GPT-2 LM are redundant as the model is not updated. If you cache the embeddings generated by GPT-2, and then set cached to True in the discriminator training script, it should be much faster.  Using the --cached flag should work! 

PS. Aside, I noticed you are using distill GPT-2 -- it's different from the GPT-2 model (medium) we use in our studies, but I suspect it should work (with slightly different hyperparameters)

**Comment by dathath** [comment]
Here are some numbers (courtesy of @w4nderlust ):


---------------------------------------
Training time without caching 50000 datapoints:
preproc 40s
each epoch 360s

Training time with caching 50000 datapoints
preproc 40s
caching 426s
each epoch 1.4s

So, you can expect a ~250 times speed up if you cache the representations for training the attribute model.
